### PR TITLE
Sort group and api with order in project config.

### PR DESCRIPTION
**Pull request by lrills**

### CODE REVIEW

**Comment by softdevstory** [comment]
I will review it.
Give me time. :)

**Comment by softdevstory** [comment]
I tried to test your code with example data in example directory, but some error occurred.

```
index.js:65
	var idx = projData.order.indexOf(name);
	                        ^

TypeError: Cannot read property 'indexOf' of undefined
```

Your code needs to handle exception.

**Comment by softdevstory** [comment]
Thanks, your codes.

**Comment by lrills** [comment]
Thanks for merging and the maintenance work! :)

**Pull request merged**
